# Generated by Django 5.0.6 on 2024-05-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(default='About Us', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='heading',
            field=models.CharField(default='Follow Us', max_length=50),
        ),
    ]
