# Generated by Django 5.0.6 on 2024-05-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_about_heading_alter_socialmedia_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='heading',
        ),
    ]
